### PR TITLE
Added exclusion list to taskbar config

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-panel/issues/1790

### CODE REVIEW

**Review by stefonarch — APPROVED** [review]
Nice feature, someone could now exclude conky on wayland :)

**Comment by tsujan** [comment]
> someone could now exclude conky on wayland

You didn't test it under X11?

**Comment by stefonarch** [comment]
> You didn't test it under X11?

Uh, forgot. A moment please.

**Comment by stefonarch** [comment]
No issue found under X11

**Comment by tsujan** [comment]
Thanks!

It shows that our backend system is nice.

**Comment by stefonarch** [comment]
_Comma separated list of window classes_ : Wondering of that should be reworded for average users in other languages too.  _Comma separated list of applications (window classes)_

**Comment by tsujan** [comment]
I used "class" intentionally because the class name may be different.

> not everbody has it clear what a "window class" could be.

Check the option above it ;)

**Comment by stefonarch** [comment]
>Check the option above it ;)

I know, but there the user can check it blindly and just look what happens. In other languages it can be strange, I notice that in the above option the text is ` Use icons by WindowClass, if available`, some didn't translate it all:

https://translate.lxqt-project.org/search/lxqt-panel/plugin-taskbar/?offset=1&q=class&sort_by=-priority%2Cposition&checksum=

**Comment by tsujan** [comment]
The window class isn't necessarily the executable name. KDE's systemsettings also uses the term. We can't replace it with an arbitrary word just because users or translators may be confused.

**Pull request merged**
