### PR TITLE
Removes deprecated QImage::byteCount()

### PR DESCRIPTION
**Pull request by luis-pereira**
Use QImage::sizeInBytes() instead.

### CODE REVIEW

**Comment by tsujan** [comment]
Like in https://github.com/lxqt/screengrab/pull/190, we need Qt ≥ 5.10 here. It's time to forget Qt 5.7 everywhere, IMO.

**Comment by luis-pereira** [comment]
> Like in [lxqt/screengrab#190](https://github.com/lxqt/screengrab/pull/190), we need Qt ≥ 5.10 here. It's time to forget Qt 5.7 everywhere, IMO.

Thanks,
I agee with that. Updated Qt required version.

**Comment by tsujan** [comment]
I'll also do it in my PR tomorrow.

**Comment by luis-pereira** [comment]
@yan12125 Travis builds are failing. The xproto package is not installed or properly installed. Can you pls take a look ?

**Comment by yan12125** [comment]
Yep there is a recent breaking change in Arch Linux regarding how to handle X11 packages [1]. Arch Linux devs are still discussing whether to revert it or not [2]. The new dependency added in 748fe90a4633d52a941313d9473731a8512236ff might not be needed in the long term.

[1] https://bugs.archlinux.org/task/64892
[2] https://lists.archlinux.org/pipermail/arch-dev-public/2019-December/029767.html

**Comment by luis-pereira** [comment]
@yan12125 Thanks

**Comment by yan12125** [comment]
Arch devs reverted the breaking change. I dismissed the workaround, too.

**Pull request merged**
