### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-panel/panel/) for LXQt Panel/Panel.

### CODE REVIEW

**Comment by stefonarch** [comment]
```
 checking package integrity...
error: libinih: signature from "Maxime Gauduin <alucryd@gmail.com>" is marginal trust
:: File /var/cache/pacman/pkg/libinih-55-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.
Error: Process completed with exit code 1.
```
@yan12125 any idea how to fix that?

**Comment by stefonarch** [comment]
Just noticed that I have this issue too :)
`pacman -Sy archlinux-keyring`

**Comment by tsujan** [comment]
A similar problem happened here a few days ago; solved by upgrading `manjaro-keyring` and `archlinux-keyring`.

**Comment by yan12125** [comment]
Yep, the keyring should be updated first. The fix for CI is a little more complex - see my pushed commit https://github.com/lxqt/ci/commit/a792e1bf9ad2935e795ecc4450663c570af6a7d8

**Pull request merged**
