### PR TITLE
tray: Proxy xembed tray icons to SNI

### PR DESCRIPTION
**Pull request by palinek**
Port of the plasma-workspace's xembed-sni-proxy.

Based on:
https://github.com/KDE/plasma-workspace/tree/e294f6ab083e2e51464b3710e9449e7aec615ce7/xembed-sni-proxy
https://github.com/KDE/plasma-workspac://invent.kde.org/plasma/plasma-workspace/-/tree/e294f6ab083e2e51464b3710e9449e7aec615ce7/xembed-sni-proxy

### CODE REVIEW

**Comment by palinek** [comment]
With this we will have only one visual "tray" widget -> the SNI one.

Or we can go even one step further and incorporate the whole proxy logic into status notifier plugin.

**Comment by stefonarch** [comment]
This works :) 
Tested with pidgin and nm-applet, right click menu working.
The cli fails because of  missing `libxslt`.

**Comment by palinek** [comment]
> The cli fails because of missing libxslt

What CLI are you talking about?

**Comment by stefonarch** [comment]
Sorry mistyped: ci (the check here).

**Comment by tsujan** [comment]
While appreciating the work that's done here, on the one hand, and not being fond of Wayland, on the other hand, I think that the current situation in Linux is an undeniable fact.

Caring for apps with old codes may be good but not at the cost of uncontrolled X11 dependencies. The tray's dependency on X11 will add to our existing troubles *unless it's confined to the tray and its use isn't encouraged by LXQt*.

**Comment by palinek** [comment]
I see no problem here, as the dependency is strictly isolated to tray plugin. As long as the dependencies are available, there should be no problem for keeping the tray code incorporated. Should the dependencies disappear or be problematic in any way, there would be no problem to remove tray plugin also.

**Comment by palinek** [comment]
Any objection?

**Comment by tsujan** [comment]
> Any objection?

I won't have time to read the code, but if it has passed enough tests, no objection from me.

**Comment by stefonarch** [comment]
The README should be updated accordingly.

**Comment by stefonarch** [comment]
Hadn't time to test before, but it looks that icon size now is buggy, icons are always the same size:

schermata-03-09-13-59

**Pull request merged**
