### PR TITLE
Make fancymenu default menu

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
I have no problem with this, but I think we may want to wait a little longer before merging it. IMHO, at least https://github.com/lxqt/lxqt-panel/issues/2000 needs to be implemented (I'll work on it).

**Comment by stefonarch** [comment]
There is no haste, and it will affect only new installations or newly added users.

**Comment by tsujan** [comment]
I think Fancy Menu is now mature enough to be the default menu. As far as I'm concerned, you could ship this whenever it's ready.

**Comment by stefonarch** [comment]
IMO `autoSel=true` has to be added now.

**Comment by tsujan** [comment]
> IMO autoSel=true has to be added now.

I'll have no problem with anything you see fit here.

**Comment by stefonarch** [comment]
> I'll have no problem with anything you see fit here.

Promise? ;)

**Comment by stefonarch** [comment]
We could consider to add to fancymenu in the default panel already 2 or 3 default favorites: browser, filemanager and eventually email client, which call the default applications.
```

[Desktop Entry]
Name=Browser Web
GenericName=Default browser
Comment=Start default browser
Exec=bash -c "$(basename -s .desktop $(qtxdg-mat def-web-browser))"
Type=Application
Categories=Network;
Icon=web-browser
Terminal=false
```
similar for default filemanager and eventually email client. To ship in `lxqt-menu-data`.

**Comment by tsujan** [comment]
"Favorite" implies "personal". I don't think we should add any favorites by default. Instead, we can add a very short explanation inside an empty Favorites section, like:  "Add your favorites by right clicking items."

**Comment by stefonarch** [comment]
With https://www.youtube.com/watch?v=jBcQT6dG3pI done merging now.

**Comment by tsujan** [comment]
Yes, Fancy Menu is ready to be used by default.

Previously I thought I wouldn't like such a menu because it would require extra clicks. But with auto-selection, it feels more comfortable than Main Menu.

**Comment by stefonarch** [comment]
As I mentioned often, I use shortcuts, 3-4 quicklaunch items and runner for the rest, it's easier with center screen and using keyboard only. I've hack for a shortcut for the menu but full  keyboard navigation in the menu isn't implemented yet. But I use the menu for checking what I've installed periodically, and I like the "All application" category very much for that purpose.

**Comment by tsujan** [comment]
> full keyboard navigation in the menu isn't implemented yet.

It'll be easy to implement if my proposal at https://github.com/lxqt/lxqt-panel/issues/1986#issue-2090312681 is acceptable.

**Comment by AzumaHazuki** [comment]
Would it be possible to add a 0ms/instant option for autoselection? Even 50ms feels a little laggy to me.

**Comment by tsujan** [comment]
> Would it be possible to add a 0ms/instant option

The shorter the delay, the more CPU usage, which would practically be for nothing with < 50ms.

> Even 50ms feels a little laggy to me.

If your feeling wasn't caused by auto-suggestion, you should have felt your time was wasted by all menus, because the delay of sub-menu popup is 256 ms by default, 225 with Fusion, 150 with Breeze, and 225 with GTK, the shortest delay being that of Motif, which is 96.

Menu-items may be selected instantly, but sub-menus appear with a delay. In Fancy Menu, categories are selected with a delay, but their corresponding apps are shown instantly.

**Pull request merged**
