### PR TITLE
Split DesktopSwitch and MoveToDesktop

### PR DESCRIPTION
**Pull request by marcusbritanicus**

### CODE REVIEW

**Comment by tsujan** [comment]
@marcusbritanicus 
Your branch isn't up-to-date. Your patch seems to reverse all the work done in [https://github.com/lxqt/lxqt-panel/pull/2102 and perhaps https://github.com/lxqt/lxqt-panel/pull/2105](https://github.com/lxqt/lxqt-panel/commit/de75344d391d205caa48123639c02c8b1b0bf5cc) and perhaps https://github.com/lxqt/lxqt-panel/commit/8fa75ed8b0feed6a1d83fd1630f1fcc8440321d8

**Comment by marcusbritanicus** [comment]
@tsujan Should be fixed now.

**Comment by tsujan** [comment]
So fast! Thanks.

**Comment by tsujan** [comment]
> but don't think it is :)

Just a self-annoying perfectionism of mine. You may not believe me that I logged into LXQt+Openbox minutes ago to test something that I was sure should work ;)

**Pull request merged**
