### PR TITLE
Some manual string conversions

### PR DESCRIPTION
**Pull request by agaida**
@tsujan - i hope i get the string parts useful - but no clue about the remaining things - the enums and windowclass

### CODE REVIEW

**Comment by tsujan** [comment]
It seems good. I'll test and add commits if needed. Will tell you when tests are finished.

BTW, I don't know what this new "continuous-integration" is but it reports "failed". (Frankly, I don't like it.)

**Comment by agaida** [comment]
it should fail - and must fail - thats the downside of ci  - it can only work with current things, esp when something important has changed

**Comment by tsujan** [comment]
Done. Please test and merge. After that, I'll test it too.

"continuous-integration" doesn't fail anymore. So, it's a good check and I should like it ;)

**Comment by agaida** [comment]
Looks and works fine for me GTM

**Pull request merged**
