### PR TITLE
Last fixes

### PR DESCRIPTION
**Pull request by stefonarch**
Removed dots, removed garbage, renamed th_Th > th, ro_RO, removed empty (not translated) files.
Related:
lxqt/lxqt#1208
lxqt/lxqt#1044
Closes lxqt/lxqt#1893

### CODE REVIEW

**Comment by tsujan** [comment]
Travis says, "All checks have failed."

**Comment by stefonarch** [comment]
Clicking "details":
`...anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
See 'docker run --help'.
The command "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash" exited with 125.
Done. Your build exited with 1..`

No idea about how travis works. And on top:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

**Comment by yan12125** [comment]
I hit "Restart build" at Travis CI and it's green now.

That error message seems a result of recently enforced rate limit from Docker Hub: https://www.docker.com/increase-rate-limits

> The rate limits of 100 container image requests per six hours for anonymous usage

All LXQt tests are running on Arch-based Docker images, and I guess the limit is counted per IP. If some other project also uses Docker on the same Travis CI virtual machine, the limit is easily hit.

In the long term, if such errors occur often, we may need to find a platform that caches Docker imgaes or even establish our own testing platform.

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

Haven't had time to investigate it. I guess the migration is automatic and transparent to users.

**Comment by stefonarch** [comment]
Thanks for investigation and all!

**Pull request merged**
