### PR TITLE
desktopswitch: Allow translation of "desktop"

### LINKED ISSUE #1498: minor translation issue desktopswitching config menu
Desktop label in the field of configuration menu of desktopswitching is not trasnslated.
See image
screen-3
Not of big concerns, but perhaps missing  translation function in desktopswitchconfiguration.cpp.

### PR DESCRIPTION
**Pull request by palinek**
fixes #1498

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM

schermata-07-11-34-27

**Comment by palinek** [comment]
@stefonarch your screenshot doesn't show the now allowed translation of default desktop name.

**Comment by mkkDr2010** [comment]
Fixed. 
screen-4

**Comment by stefonarch** [comment]
> your screenshot doesn't show the now allowed translation of default desktop name

Here one from a new user, not sure where the names come from, obconf/openbox has "(Desktop senza nome)"

screen

**Pull request merged**
