### PR TITLE
Update build.sh for Qt6

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Looks GTM.

**Comment by stefonarch** [comment]
It still fails at  

```
CMake Error at CMakeLists.txt:37 (find_package):
  By not providing "FindQt6DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6DBus"
  (requested version 6.6.0) with any of the following names:

    Qt6DBusConfig.cmake
    qt6dbus-config.cmake

  Add the installation prefix of "Qt6DBus" to CMAKE_PREFIX_PATH or set
  "Qt6DBus_DIR" to a directory containing one of the above files.  If
  "Qt6DBus" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
Error: Process completed with exit code 1.
```
no clue... @yan12125 ?

**Comment by Chiitoo** [comment]
Isn't it missing the 'libdbusmenu-lxqt' package [1], or am I looking at the wrong place?

1. https://github.com/lxqt/lxqt-panel/actions/runs/8434414844/job/23097589406#step:5:386

**Comment by stefonarch** [comment]
It fails there now? I fixed that too:
https://github.com/lxqt/lxqt-panel/blob/daaadff170f3cc0c826711cd1b14689a3eba17bb/.ci/build.sh#L6

**Comment by stefonarch** [comment]
It looks like there is no libdbusmenu-lxqt yet...
https://github.com/lxqt/lxqt-panel/pull/2042

**Comment by stefonarch** [comment]
Ok, now it fails at `lxqt-globalkeys-git` and it needs the updated AUR packages I guess. so we have to wait.

**Pull request merged**
