### PR TITLE
Add default settings, remove obsolete tray

### PR DESCRIPTION
**Pull request by stefonarch**
Replaces https://github.com/lxqt/lxqt-panel/pull/1384
Related discussion: https://github.com/lxqt/lxqt/discussions/2163

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Seems reasonable to me.

**Comment by stefonarch** [comment]
Fastest PR ever :)

**Comment by tsujan** [comment]
Yes :)

Strange that we'd forgotten to remove `tray` from the default config.

**Comment by stefonarch** [comment]
We never looked at it, I noticed it only by reading the finished PR and made a `commit --amend` for it.

**Comment by slidinghotdog** [comment]
IMO #1384 should still be merged (and change the default in code for the others too) so when adding a new panel/plugin it gets the same defaults, what do u think @tsujan @stefonarch ?

**Comment by tsujan** [comment]
My opinion:

"An app should be customized through its config, not in its code."

And:

"For every argument for the default value of an option, there's a counterargument — unless that option is weird (then, why having it in the first place?) — because tastes and habits differ."

I think the wise thing was done in this PR.

**Comment by stefonarch** [comment]
I agree, and ìf we decide to change once we can do it easily. And anyway if distro maintainers care they will change many of them.
But there is a point: if people add a second menu and add mainmenu e/o taskbar to it they have to start from zero, but I think most users will not do so and the power twiddlers will be happy to tweak all.

Thinking about the panel  configurations https://github.com/lxqt/lxqt-panel/issues/1581 comes to my mind.

**Comment by slidinghotdog** [comment]
> But there is a point: if people add a second menu and add mainmenu e/o taskbar to it they have to start from zero, but I think most users will not do so and the power twiddlers will be happy to tweak all.

I just think it's weird for the new plugin to have a different config than the default one.
Whatever the default config is, it should be the same in both cases.

**Pull request merged**
