### PR TITLE
mainmenu: Use new signal/slot connection notation

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by palinek** [comment]
@MaxKrummenacher can you, please, check if this builds correctly with the 5.11..

**Comment by agaida** [comment]
@palinek - i will do soon - yesterday rebuilt the whole LXQt with Qt 5.11 rc1 - works fine so far, ok, breaks on the not merged things.

**Comment by agaida** [comment]
@palinek - panel works fine here too - the only thing that feels broken right now is pcmanfm-qt - but maybe it's just me.

**Comment by agaida** [comment]
the pcmanfm-qt issue was already filed: lxqt/libfm-qt/issues/164 - so no problem to merge it

**Pull request merged**
