### PR TITLE
Make menus more consistent and intuitive

### PR DESCRIPTION
**Pull request by libalis**
Before all: very first pull request ever, so sorry for everything.

This pull request changes the following things:

1. I noticed an ugliness in the formatting.

2. The about dialog has moved to the bottom.
This is more consistent and intuitive in my opinion, as it is a rather unimportant item.
An application menu should probably have the applications at the top.

3. Made separators consistent.

Opinions are welcome.

### CODE REVIEW

**Comment by ianfarrell47** [comment]
This is a helpful change from a UX perspective. Now the XDG menu is at the top.

**Comment by stefonarch** [comment]
I didn't think of inverting all, just about "search" and maybe "leave" on top.

**Comment by ianfarrell47** [comment]
From a UX perspective, I believe that the XDG menu should be at the top. The alternative menus are great and I feel this PR improves them.

**Comment by ianfarrell47** [comment]
It is really a matter of taste. After testing the .menu files, I see we can group the menu items as:
- XDG menu
- Preferences
- About
- Leave/Lock
(in no particular order.)

These groups can be inverted for top-orientation panels. Whether About is moved below the XDG menu, I still believe makes sense due to the XDG menu having priority.

**Comment by ianfarrell47** [comment]
I believe the applications menu is most important, and the separator and formatting fixes are good, so this should go through in my opinion.

**Pull request closed without merging**
