### PR TITLE
Fixed compilation against Qt 5.12/13

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-panel/issues/1472

### CODE REVIEW

**Comment by luis-pereira** [comment]
Looks Ok. But didn't try to build it. Lack of time.

**Comment by tsujan** [comment]
I built it twice: as it was and also, by changing the version checks to `QT_VERSION_CHECK(5,16,0)` (to use the old code). It compiled well. But will wait for your test; mistakes are never impossible.

**Review by luis-pereira — APPROVED** [review]
GTM.
Built with Qt 5.12.9 and Qt 5.13.2.

**Comment by tsujan** [comment]
> Built with Qt 5.12.9 and Qt 5.13.2.

Wow! That's a very complete test. Thanks!

**Pull request merged**
