### PR TITLE
Added a label for empty Favorites to Fancy Menu

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Review by stefonarch — APPROVED** [review]
Did test hard,but found nothing.
>.. by right clicking items from other categories

"other" could be removed here IMO

**Comment by tsujan** [comment]
> "other" could be removed here IMO

How?

**Comment by stefonarch** [comment]
I know, but we won't assume that users want to add favorites from the favorites category, do we?

**Comment by tsujan** [comment]
OK, I'll change it to "... from categories". Is that good?

**Comment by stefonarch** [comment]
> OK, I'll change it to "... from categories". Is that good?

Sure thanks!

**Pull request merged**
