### PR TITLE
Fixed taskbar, removed tray section

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Taskbar settings weren't at the right place.

**Comment by palinek** [comment]
Why would we want to remove tray?

**Comment by tsujan** [comment]
We announced it deprecated. Very old (usually GTK2 apps) may use it.

**Comment by stefonarch** [comment]
It will be added when tray widget is added, no need to have it by default.

**Comment by slidinghotdog** [comment]
If #1721 is merged it would be good to have tray as default.

**Comment by tsujan** [comment]
> If #1721 is merged it would be good to have tray as default.

Tray depends on X11 heavily. Although we don't have a Wayland session, we've avoided X11 as far as possible.

**Comment by stefonarch** [comment]
My understanding is that tray can be removed completely when https://github.com/lxqt/lxqt-panel/pull/1721 is merged (but  it needs  `xembedsniproxy`  process to be started - may by checkbox a "support legacy tray in SNI")

**Comment by palinek** [comment]
>  (but it needs xembedsniproxy process to be started - may by checkbox a "support legacy tray in SNI")

No. It is implementing the xembedsniproxy directly in panel. No other external dependency.

**Comment by stefonarch** [comment]
So to activate  support for legacy apps users should simply add the tray plugin which will stay invisible?

**Comment by palinek** [comment]
Yes. Now the tray does not have a widget, it just "translates" the icons/menus/etc. to SNI.

**Comment by stefonarch** [comment]
But it's only activated when added to the panel? If so the description should be changed accordingly.
```
Desktop Entry/Name: "System Tray"
Desktop Entry/Comment: "Obsolete; please use Status Notifier Plugin!"
```

**Comment by palinek** [comment]
https://github.com/lxqt/lxqt-panel/pull/1721/files#diff-a5e53b802a2c99bc3f404f0d300875f049e17563ffb17296577bd33f20413886L2

**Comment by stefonarch** [comment]
It's not displayed without updating  translations I see.
`Maps obsoleted xembed icons to Status Notifier ones` could be shorter: `Maps obsolete xembed icons to Status Notifier`, not sure how many people understand also "xembed".

**Comment by stefonarch** [comment]
> If #1721 is merged it would be good to have tray as default.

Readded now.
 [tray] in panel.conf will never be used anymore as the new tray has no settings.

Anything else we could/should ship in default settings for the panel?

**Comment by palinek** [comment]
> [tray] in panel.conf will never be used anymore as the new tray has no settings

Even with no configuration, the `type` must be there. Am I missing something?

**Comment by stefonarch** [comment]
I tested a fresh user, `[tray`] is initally not present in `panel.conf` after adding it in fact  those settings appear:
```
[tray2]
alignment=Right
type=tray
```
No idea if they have effect and/or are needed, "alignment" theoretically could impact RTL languages.

**Comment by stefonarch** [comment]
Can this be merged? See https://github.com/lxqt/lxqt-session/pull/424#issuecomment-1086562637

**Comment by tsujan** [comment]
Merge it and do your tests.

**Pull request merged**
