### PR TITLE
Qt5 signal/slots change

### PR DESCRIPTION
**Pull request by adjamhub**
Plugins: mount, networkmonitor (just two, as promised)
:)

### CODE REVIEW

**Comment by tsujan** [comment]
> just two, as promised

Thanks :) Believe me, a review is harder than it may seem (take a look at https://github.com/lxqt/lxqt-globalkeys/pull/210).

**Comment by adjamhub** [comment]
> > just two, as promised
> 
> Thanks :) Believe me, a review is harder than it may seem (take a look at [lxqt/lxqt-globalkeys#210](https://github.com/lxqt/lxqt-globalkeys/pull/210)).

Argh.... I see. Sorry for that :(

**Comment by tsujan** [comment]
No need to be sorry. It was *my* job to see it.

**Review by tsujan — APPROVED** [review]
GTM

**Pull request merged**
