### PR TITLE
fix for menu overlap

### PR DESCRIPTION
**Pull request by slidinghotdog**
fix for #1483
at first i wanted to emit a signal from panel to let the menu recalculate its position, but thought this one would be better since it's a more generic fix (although i don't know if there's another popup u can open with key shortcut)

### CODE REVIEW

**Comment by stefonarch** [comment]
Tested and working fine, thanks!

**Comment by slidinghotdog** [comment]
Oh i didnt account for animations, ill have to fix it later

**Comment by slidinghotdog** [comment]
ok now it doesn't matter if the panel is hidden, the menu will always show in the expected position even with animations... code is also a lot simpler..

**Review by tsujan — APPROVED** [review]
The logic seems correct. I couldn't find a problem in it.

LGTM.

**Comment by stefonarch** [comment]
Tested again, all ok. Thanks!

**Pull request merged**
