### PR TITLE
Backlight plugin

### PR DESCRIPTION
**Pull request by selairi**
This is a simple plugin to change the backlight of the display.
backlight-plugin

### CODE REVIEW

**Comment by tsujan** [comment]
I'll test it today (sorry for the delay; have been very busy with coding).

**Comment by tsujan** [comment]
This is a useful plugin and it works fine but there are 3 small issues as far as I tested:

 1. When I click on `m_upButton` or `m_downButton`, nothing happens. The reason is that the value is changed only by 1, while I have "5273" in `/sys/class/backlight/intel_backlight/max_brightness` ;) I think the brightness should change by the maximum of 1 and 1% of the max brightness: `qMax(1, maxBrightness/100)`.

 2. I agree that it's better not to change the brightness by turning the mouse wheel over its icon on the panel (that prevents mistakes). However, for me, the brightness doesn't change either when the mouse wheel is over the slider. The reason is the same as above: with a max. brightness of "5273", the wheel practically does nothing.

 3. IMHO, the places of the characters `☼` and `☀` should be reversed; the former is more suitable for "darker" and latter for "brighter".

**Comment by selairi** [comment]
>     1. When I click on `m_upButton` or `m_downButton`, nothing happens. The reason is that the value is changed only by 1, while I have "5273" in `/sys/class/backlight/intel_backlight/max_brightness` ;) I think the brightness should change by the maximum of 1 and 1% of the max brightness: `qMax(1, maxBrightness/100)`.

Done.

>     2. I agree that it's better not to change the brightness by turning the mouse wheel over its icon on the panel (that prevents mistakes). However, for me, the brightness doesn't change either when the mouse wheel is over the slider. The reason is the same as above: with a max. brightness of "5273", the wheel practically does nothing.

Done

>     3. IMHO, the places of the characters `☼` and `☀` should be reversed; the former is more suitable for "darker" and latter for "brighter".

Done.

Thanks for your suggestions.

**Comment by tsujan** [comment]
It works very well.

GTM.

**Comment by tsujan** [comment]
@selairi 
Please squash your sub-commits in a PR before merging it; otherwise, it'll be difficult to find them when making changelogs or searching for bugs.

Squashing of the last 2 sub-commits can be done by
```
git reset --soft HEAD~2
git commit
```
And then `push` (to branch). And similarly for 3, 4,... sub-commits.

**Pull request merged**
