### PR TITLE
Fancy Menu: Workaround for lack of context menu with Qt 6.8.0

### PR DESCRIPTION
**Pull request by tsujan**
Qt 6.8.0 suppresses context menus when the window has the `Qt::Popup` flag.

Closes https://github.com/lxqt/lxqt-panel/issues/2145

### CODE REVIEW

**Comment by palinek** [comment]
Events going to `mAppView`'s widget are already watched. How about just adding the logic there?:
```diff
diff --git a/plugin-fancymenu/lxqtfancymenuwindow.cpp b/plugin-fancymenu/lxqtfancymenuwindow.cpp
index 7a36ca1e..05087460 100644
--- a/plugin-fancymenu/lxqtfancymenuwindow.cpp
+++ b/plugin-fancymenu/lxqtfancymenuwindow.cpp
@@ -174,13 +174,16 @@ LXQtFancyMenuWindow::LXQtFancyMenuWindow(QWidget *parent)
     mAboutButton->setToolTip(mAboutButton->text());
     connect(mAboutButton, &QToolButton::clicked, this, &LXQtFancyMenuWindow::runAboutgDialog);
 
+    // NOTE: Qt 6.8.0 has a bug that does not allow context menus with the Qt::Popup flag.
+    // As a workaround, we set the context menu policy to Qt::PreventContextMenu and handle
+    // the RightButton press/releases in eventFilter.
     mAppView = new QListView;
     mAppView->setObjectName(QStringLiteral("AppView"));
     mAppView->setSelectionMode(QListView::SingleSelection);
     mAppView->setDragEnabled(true);
     mAppView->setMovement(QListView::Snap);
     mAppView->setDropIndicatorShown(true);
-    mAppView->setContextMenuPolicy(Qt::CustomContextMenu);
+    mAppView->setContextMenuPolicy(Qt::PreventContextMenu);
     mAppView->setItemDelegate(new SeparatorDelegate(this));
 
     // label for empty Favorites
@@ -212,7 +215,7 @@ LXQtFancyMenuWindow::LXQtFancyMenuWindow(QWidget *parent)
 
     connect(mAppModel, &LXQtFancyMenuAppModel::favoritesChanged, this, &LXQtFancyMenuWindow::favoritesChanged);
     connect(mAppView, &QListView::activated, this, &LXQtFancyMenuWindow::activateAppAtIndex);
-    connect(mAppView, &QListView::customContextMenuRequested, this, &LXQtFancyMenuWindow::onAppViewCustomMenu);
+    //connect(mAppView, &QListView::customContextMenuRequested, this, &LXQtFancyMenuWindow::onAppViewCustomMenu);
     connect(mCategoryView, &QListView::activated, this, &LXQtFancyMenuWindow::activateCategory);
     connect(mCategoryView->selectionModel(), &QItemSelectionModel::currentChanged,
             this, &LXQtFancyMenuWindow::activateCategory);
@@ -544,6 +547,19 @@ bool LXQtFancyMenuWindow::eventFilter(QObject *watched, QEvent *e)
         else if (e->type() == QEvent::Leave)
             mAutoSelTimer.stop();
     }
+    else if (e->type() == QEvent::MouseButtonRelease
+             && (watched == mAppView->viewport()))
+    {
+        QMouseEvent *ev = static_cast<QMouseEvent *>(e);
+        if (ev->button() == Qt::RightButton)
+        {
+            onAppViewCustomMenu(ev->position().toPoint());
+            ev->accept();
+            return true;
+        }
+    }
 
     return QWidget::eventFilter(watched, e);
 }
```

**Comment by tsujan** [comment]
> How about just adding the logic there?

It's a very good idea and simplifies the patch. Would you add a commit to the PR?

**Comment by palinek** [comment]
Done

**Comment by tsujan** [comment]
Shouldn't `else if (e->type() == QEvent::MouseButtonRelease` be before `else if (mAutoSel` ?

**Comment by palinek** [comment]
You're absolutely right, moved.

**Comment by tsujan** [comment]
Works fine. Merging?

**Comment by tsujan** [comment]
Oh, there is a problem: right clicking an item doesn't select it because the menu is shown before `eventFilter` returns.

**Comment by tsujan** [comment]
I think we shouldn't accept the event or return true but use a singleShot timer and change
```c++
connect(mAppView, &QListView::activated, this, &LXQtFancyMenuWindow::activateAppAtIndex);
```
to
```c++
connect(mAppView, &QListView::clicked, this, &LXQtFancyMenuWindow::activateAppAtIndex);
```
I'm testing it...

**Review by palinek — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
The Qt bug is fixed in 6.9.2; at least, I can't reproduce it under Wayland, in Fancy Menu's line-edit (filter) or other places. But the workaround is safe.

**Comment by tsujan** [comment]
> The Qt bug is fixed in 6.9.2; **at least**

OK, by pure chance and for a totally different reason (long and boring story), I had to downgrade Qt to 6.9.1 and upgrade it to 6.9.2 again. The issue was present in the first and fixed in the second.

**Pull request merged**
