### PR TITLE
Allow multiple StatusNotifierWidgets, no.2

### PR DESCRIPTION
**Pull request by palinek**
Supersedes #1618

@slidinghotdog Please, test/review/compare my changes.

Note: optimization for not duplicating icons, menus etc. is left for future PRs. We should create an issue for it, when this is merged.

### CODE REVIEW

**Comment by slidinghotdog** [comment]
@palinek Your changes looks good, it's simpler and i don't see any problems with it. I'm using it and haven't noticed any problems, i'll keep a few extra status notifiers for further testing.

**Comment by palinek** [comment]
Any objection merging this?

**Comment by palinek** [comment]
It passed my testing, multiple instances with different configurations/hiding options...

**Comment by tsujan** [comment]
Merge it. I started to use it now. @slidinghotdog's code seemed OK; yours is better.

**Review by tsujan — APPROVED** [review]
Works fine.

**Pull request merged**
