### PR TITLE
WIP: Spacer expandable

### PR DESCRIPTION
**Pull request by palinek**
Add possibility for spacer plugin to be auto-expandable.

closes lxde/lxqt#1038

### CODE REVIEW

**Comment by stefonarch** [comment]
You are fast, thanks!
 It seems working fine, maybe options for dotted and lined could be disabled making invisibile default when "expanded" is selected, otherwise you get a line in the middle.
schermata

**Comment by palinek** [comment]
> maybe options for dotted and lined could be disabled making invisibile default when "expanded" is selected, otherwise you get a line in the middle.

The choice is on user side. I think it (visible line) can be usefull for some people.

**Comment by palinek** [comment]
@paulolieuthier, @luis-pereira, @tsujan Can you, guys, review this? thanks

**Comment by tsujan** [comment]
@palinek  It works as intended here. Sorry, I'm wrestling with a libfm-qt problem and can't examine the code now but I trust your work. So, GTM.

**Comment by luis-pereira** [comment]
@palinek My only suggestion is the use of `QLatin1String`/`QStringLiteral`.
GTM

**Comment by luis-pereira** [comment]
Talked to early
@palinek Check this:
screen-2016-05-05-20-38-28 png
screen-2016-05-05-20-39-06 png

**Comment by tsujan** [comment]
I saw what @luis-pereira meant but *not as a problem.*

**Comment by palinek** [comment]
@luis-pereira do you mean that if both taskmanger and spacer are expandable, then the taskmanager overtakes the space?
This is done by the logic of the "expansion" in [panellayout](https://github.com/lxde/lxqt-panel/blob/master/panel/lxqtpanellayout.cpp#L690) -> the "free" space is distributed proportionaly based on the "real" width/height of the widgets.

If this is a problem, what do you suggest to be the correct behaviour?

**Comment by palinek** [comment]
> My only suggestion is the use of QLatin1String/QStringLiteral.

Done.

**Comment by luis-pereira** [comment]
@palinek I'm really not sure. But I find "weird" the spacer being in the "middle" of the panel and moving back and forth. Doesn't it violates the 'Lock Panel' option ?

Did you considered using `QLatin1String` for repeated strings ?

**Comment by stefonarch** [comment]
I see a bug: adding a new spacer on the panel with the taskbar the two dialog windows from panel settings/adding widget do not disappear after closing and are dead, restarting panel solves.

**Comment by stefonarch** [comment]
I think there is a conflict when present on the same panel together with systray e/o notifier which do not heve fixed width either. Some apps like screengrab or keepassx which hide in the try  show up for one instance and disappear, beeing still open though.

**Comment by agaida** [comment]
@palinek - any news?

**Comment by palinek** [comment]
Nope... I didn't touch this one.

**Comment by palinek** [comment]
... rebased

> I see a bug: adding a new spacer on the panel with the taskbar the two dialog windows from panel settings/adding widget do not disappear after closing and are dead

I don't see this behavior... how to reproduce?

>  But I find "weird" the spacer being in the "middle" of the panel and moving back and forth.

Yes... if now more than one widget is "expandable", you can configure the panel to do funny things.

**Comment by agaida** [comment]
@palinek - works fine as far as i can see - the funny things included - for me GTM

**Pull request merged**
