### PR TITLE
updated *.ts files

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
@yan12125 Any idea about this alpm error?
```
Run bash ./.ci/build.sh
+ cat
+ pacman -Syu --noconfirm
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
Error: Process completed with exit code 255.
```

**Comment by yan12125** [comment]
No idea, and I cannot reproduce the issue on my machine...

**Comment by stefonarch** [comment]
> No idea, and I cannot reproduce the issue on my machine...

But isn't this an error on the check machine?

**Comment by yan12125** [comment]
OK, I guess I know the issue. Haven't had time to write a complete explanation. Some notes:

* A workaround: https://github.com/lxqt/lxqt-panel/commit/c5ae80a40220028f6f85745bc9fbd4439df1383d
* Cause: https://sourceware.org/git/?p=glibc.git;a=patch;h=3d3ab573a5f3071992cbc4f57d50d1d29d55bde2
* Solution: https://github.com/moby/moby/pull/41381

**Comment by stefonarch** [comment]
I re-run the check, no change atm.

**Comment by stefonarch** [comment]
I re-run the check, no change atm.

**Comment by yan12125** [comment]
> Edit: thougt it was in master already...

Ah, I was still considering the best workaround. Now here you go~ https://github.com/lxqt/lxqt-panel/pull/1562

**Comment by yan12125** [comment]
I merge the fix and re-run CI, but seems GitHub does not merge your branch on top of the latest master. Could you rebase your patch manually?

**Comment by stefonarch** [comment]
Looks good now, thanks!

**Comment by yan12125** [comment]
Great! This PR itself looks good, too - merging.

**Comment by stefonarch** [comment]
Thanks, unlocked panel on weblate now :)

**Pull request merged**
