### PR TITLE
Fixed main popup positions under Wayland

### PR DESCRIPTION
**Pull request by tsujan**
… for bottom and right panels.

The problem was that some Wayland compositors returned global coordinates when anchors were applied, while some others (perhaps KWin) didn't. So, the patch uses local coordinates and changes them to the global ones in the end.

### CODE REVIEW

**Review by stefonarch — COMMENTED** [review]
I built it only with fancymenu to save time, it looks like there is a  positioning issue with panels < 100% width now:

immagine

immagine

**Comment by tsujan** [comment]
> It opens 2x the px …

Oh, my bad! I forgot to apply a change that I'd made here. Nice catch! It's fixed now. Please try again.

**Comment by stefonarch** [comment]
Looks fine now, nice work, it was worrying me quite a lot. Do we ship a point release?

**Comment by stefonarch** [comment]
No need to test under x11, I forgot to ask.

**Comment by tsujan** [comment]
Did you test it thoroughly under X11 too? I tested it only with top and bottom panels and also with auto-hiding under X11.

> Do we ship a point release?

I don't think so. We didn't promise a really usable Wayland support for the panel in 2.0.0, and we don't have many Wayland users of 2.0.0 (maybe no one).

**Comment by tsujan** [comment]
> No need to test under x11

Why?!

**Comment by Bluey26** [comment]
Hi i installed it and restarted panel module.

The popup position seems to be fixed, but the menu bar items are absent(all the opened windows).

This happened to me too with one of the last panels i compiled, not sure why. Reverting the panel to:

`source=("git+https://github.com/LXQt-Marcus-Fork/lxqt-panel#branch=wlroots_backend_patched")`

seems to show my window icons again, after restarting panel module.

**Comment by stefonarch** [comment]
You would need to apply the changes to @marcusbritanicus ' branch, maybe he'll include them soon.

**Comment by tsujan** [comment]
> but the menu bar items are absent

This branch doesn't contain the Wayland PRs. It's based on the master. None of the Wayland PRs is merged (because none of them is ready yet), and the master branch doesn't support task-bar on Wayland.

As I suggested in https://github.com/lxqt/lxqt-panel/issues/2084#issuecomment-2301696416, you could apply the patch to the source you used before. If that's not easy for you, you could wait until it's merged; then you could apply the patch at https://github.com/lxqt/lxqt-panel/pull/2043#issuecomment-2291517371 to the master.

**Comment by Bluey26** [comment]
Awesome! i just have managed to do it :smile:  (`git apply 2086.diff` inside the folder)

I can verify that applying that patch to this: https://github.com/LXQt-Marcus-Fork/lxqt-panel/tree/wlroots_backend_patched
and then installing using ABS as usual seems to work. I restarted the panel module and now it works. I will try to add the !2087 one too to this.

Thanks a lot for the patience, i am still learning xD

**Comment by marcusbritanicus** [comment]
Tested on wlroots_backend_patched, and another local branch... Works like a charm. @tsujan Nice catch!!

**Comment by stefonarch** [comment]
I applied the patch to Marcus' panel and see an inconistent behavior with right panel (probably the same with bottom panel):
* panel configuration popup ok
* directory menu plugin ok
*  menu + from status notifier ok

but all items inside statusnotifier have their right clicks popups at screen border.

**Comment by tsujan** [comment]
> but all items inside statusnotifier have their right clicks popups at screen border.

I intentionally used "_main_ popup" in the title. I know about quick-launch and tray right click menus under Wayland, but they're not related to this PR.

**Comment by stefonarch** [comment]
I know, thought just to mention it.

**Comment by tsujan** [comment]
And please don't forget X11. Although I think a regression should be impossible, it needs thorough tests.

**Comment by stefonarch** [comment]
Couldn't spot regressions on x11. But mainmenu is still aligned to bottom screen, but as it has  bad issues anyway (search results) on wayland bottom panels we can ignore this IMO.

**Comment by tsujan** [comment]
> Couldn't spot regressions on x11.

Thanks for checking.

> But mainmenu is still aligned to bottom screen

Its problem is like that of the other two cases. I'll investigate them later,. Let's keep this PR limited to `LXQtPanel::calculatePopupWindowPos()`, for having clean and separate commits.

**Comment by tsujan** [comment]
I did a preliminary check and found out that those cases are all related to how `QMenu::popup()` currently works under the Wayland compositors that trigger the issue. I also checked and made sure that  `LXQtPanel::calculatePopupWindowPos()` did its job correctly in their case.

**Comment by tsujan** [comment]
For future reference:

It's getting more interesting! Actually, `QMenu::popup()` completely ignores the vertical positioning with a bottom panel under Wayland.

I tested it in both main-menu and status notifier by using `QMenu::popup(POSITION - QPoint(100, 100)`. While the horizontal position was respected, the vertical one was ignored.

So, the problem can be in QtWayland or layer-shell-qt or on a more basic level, but it isn't in our code.

**Comment by marcusbritanicus** [comment]
If I understand correctly (I can be way off the mark on this one), on wayland, we have something called the xdg-positioner. It's duty is to position the popup. The values you give it are calculated relative to the parent. There are also options to set the anchor, gravity, size and so on.

It is quite possible that Qt is doing something wrong here. Or perhaps, Qt is moving the popup that's going "out of the screen", or something like that.

**Comment by tsujan** [comment]
> It is quite possible that Qt is doing something wrong here.

I agree. Since it doesn't happen when we show a popup explicitly, it may be in `QMenu::popup()` or some function that it calls. I might check it later.

**Review by stefonarch — APPROVED** [review]

**Comment by tsujan** [comment]
I got bored and did another test, by using `QMenu::setGeometry()` plus `QMenu::show()` instead of `QMenu::popup()`. And it worked: the menu was shown at the correct position. It also proves that `QMenu::popup()` has a problem under Wayland. However, it's not a good workaround — at least not for Main Menu or Status Notifier — because it doesn't affect submenus or tooltips.

The fact that tooltips are also affected points to a deeper cause inside Qt.

**Pull request merged**
