### PR TITLE
Americanizing

### PR DESCRIPTION
**Pull request by tsimonq2**
https://github.com/lxqt/lxqt/issues/1519

### CODE REVIEW

**Comment by jubalh** [comment]
Is american english more valid for a Changelog that british english? :)

**Comment by tsujan** [comment]
@jubalh We agreed to do it as KDE does, with the American En as the default language.

**Comment by jubalh** [comment]
I see, wasn't aware of this.

**Comment by tsujan** [comment]
@tsimonq2 *Please* don't change the code -- not even code comments, let alone function/file names! The code follows coder's styles and isn't something users deal with directly. Functions and files can have any names the programmer sees fit.

**Comment by tsujan** [comment]
AND changing a header name can have unforeseen consequences.

**Comment by luis-pereira** [comment]
I agree with @tsujan. Keep this changes user visible only. Don't change variable/functions and even less filenames.

**Comment by tsimonq2** [comment]
ACK.

**Comment by tsimonq2** [comment]
Reverted for now.

**Pull request merged**
